### ISSUE TITLE
Not saving sessions.

### ISSUE THREAD

**Issue by johnmiller86** [scottlininger/zelda30tribute#2]
I am curious to how the original server was setup as far as cookies/session vars, it works perfectly on my web server aside from saving.

**Comment by scottlininger** [comment]
The game uses the localStorage API to record state. No cookies and nothing server side.

What browser are you using?

**Comment by johnmiller86** [comment]
I have tried both Chrome and Firefox.

**Comment by johnmiller86** [comment]
I'm not sure exactly what happened, definitely something on my end.  I re-uploaded it and now it works.  Thank you for your quick response and your amazing work!
