### ISSUE TITLE
How do i set up a local webserver?

### ISSUE THREAD

**Issue by ghost** [scottlininger/zelda30tribute#6]
I really want to play this game. I downloaded the files, but... How do i set up a local webserver?

**Comment by ghost** [comment]
Nevermind. I figured it out in a Google Search. If you have the same problem as me, use a program called XAMPP.

**Comment by AladdinSeaifan** [comment]
Hello,

Seems like you figured it out moments before I was going to respond. 

I'm going to leave this link here anyways. 
[How to Set Up a Local Web Server on Windows, Mac, and Linux](https://www.maketecheasier.com/setup-local-web-server-all-platforms/)
